### ISSUE TITLE
【不具合】kabu_STATION_API.yamlからAPIクライアントを生成できない

### ISSUE THREAD

**Issue by spotthediff** [kabucom/kabusapi#242]
`openapi-generator-cli`でOpenAPI v3に対応したkabu_STATION_API.yamlからAPIクライアント用のコードを生成しようとしても、コードが生成されません。

下記コマンドを実行するとエラーが発生します。

実行コマンド:
`openapi-generator-cli generate -i https://raw.githubusercontent.com/kabucom/kabusapi/master/reference/kabu_STATION_API.yaml
    -g go -o ~/api_dir
`

エラーログ: 

```
[main] INFO  o.o.codegen.utils.ModelUtils - [deprecated] inheritance without use of 'discriminator.propertyName' has been deprecated in the 5.x release. Composed schema name: null. Title: 株価情報 (種別:1~4)
[main] INFO  o.o.codegen.utils.ModelUtils - [deprecated] inheritance without use of 'discriminator.propertyName' has been deprecated in the 5.x release. Composed schema name: null. Title: 株価情報 (種別:5)
[main] INFO  o.o.codegen.utils.ModelUtils - [deprecated] inheritance without use of 'discriminator.propertyName' has been deprecated in the 5.x release. Composed schema name: null. Title: 株価情報 (種別:6)
[main] INFO  o.o.codegen.utils.ModelUtils - [deprecated] inheritance without use of 'discriminator.propertyName' has been deprecated in the 5.x release. Composed schema name: null. Title: 株価情報 (種別:7)
[main] INFO  o.o.codegen.utils.ModelUtils - [deprecated] inheritance without use of 'discriminator.propertyName' has been deprecated in the 5.x release. Composed schema name: null. Title: 信用情報（種別:8~13）
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 7, Warning count: 0
Errors: 
	-attribute info.contact.../ptal/index.html
	-attribute paths.'/wallet/margin/{symbol}@{exchange}'. Declared path parameter symbol}@{exchange needs to be defined as a path parameter in path or operation level
	-attribute paths.'/wallet/option/{symbol}@{exchange}'. Declared path parameter symbol}@{exchange needs to be defined as a path parameter in path or operation level
	-attribute paths.'/wallet/cash/{symbol}@{exchange}'. Declared path parameter symbol}@{exchange needs to be defined as a path parameter in path or operation level
	-attribute paths.'/wallet/future/{symbol}@{exchange}'. Declared path parameter symbol}@{exchange needs to be defined as a path parameter in path or operation level
	-attribute paths.'/board/{symbol}@{exchange}'. Declared path parameter symbol}@{exchange needs to be defined as a path parameter in path or operation level
	-attribute paths.'/symbol/{symbol}@{exchange}'. Declared path parameter symbol}@{exchange needs to be defined as a path parameter in path or operation level

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:541)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:568)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:424)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

**Comment by yasuyuki-nakazawa** [comment]
こちら、対応させていただきました。
しかしながら、外部ツールの稼働を今後もお約束するものではございません
可能な限り対応できるものは対応させていただきますが、上記はご認識、ご理解いただけると幸甚です。
