### ISSUE TITLE
【質問】WSLからKabuステに接続できる仕様ですか？

### ISSUE THREAD

**Issue by hysdsk** [kabucom/kabusapi#645]
■目的・背景
Windows上のWSLからKabuステAPIを使用したいです。

RESTの場合は以下の方法で接続が可能でした。
https://github.com/kabucom/kabusapi/issues/623

PUSHの場合は以下のエラーが発生して接続ができません。
```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<EntitySpec.__call__.<locals>.stream() done, defined at /home/daishaya/projects/python-kabusapi/kabusapi/websocket.py:15> exception=InvalidStatusCode(400, Headers([('Content-Type', 'text/html; charset=us-ascii'), ('Server', 'Microsoft-HTTPAPI/2.0'), ('Date', 'Mon, 06 Mar 2023 00:13:55 GMT'), ('Connection', 'close'), ('Content-Length', '339')]))>
Traceback (most recent call last):
  File "/home/daishaya/projects/python-kabusapi/kabusapi/websocket.py", line 16, in stream
    async with websockets.connect(self.uri,
  File "/home/daishaya/.local/lib/python3.10/site-packages/websockets/legacy/client.py", line 642, in __aenter__
    return await self
  File "/home/daishaya/.local/lib/python3.10/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home/daishaya/.local/lib/python3.10/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/home/daishaya/.local/lib/python3.10/site-packages/websockets/legacy/client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 400
```
上記のエラーがWSLからの接続が理由かわかりませんが、切り分けのために質問させてください。

■質問
WSLからは接続できない仕様となっていますでしょうか？そういった仕様の場合の理由などもご教示いただけると幸いです。

**Comment by yasuyuki-nakazawa** [comment]
カブステが稼働している端末とWSLが稼働している端末は同一端末という認識でよろしいでしょうか
RESTが成功しているということで、同じと想像しています。
Socket接続エラーですね。ご質問いただいている環境下で稼働させている実績がないですが、想定原因をお出しできるか内部に持ち帰ってみます。

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa 
> 同一端末という認識でよろしいでしょうか

Kabuステが稼働しているWindowsとWSLのホストのWindowsは同一端末でございます。本件で失敗したコードをWindows上で実行したところ、PUSHの受信に成功しました。ですので恐らくWSL上からホストのWindowsのポート接続に何かしらの制限がかかっていると思いました。

> 想定原因をお出しできるか内部に持ち帰ってみます。

よろしくお願いいたします。RESTと同じように、制限の解除方法などございましたら幸いです。

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa こちら、その後いかがでしょうか？

**Comment by enasu** [comment]
同じ状況にあります。
wsl上のdocker container を起動時に `-p 18080:18080`とポートフォワードを行うと
`docker: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:18080 -> 0.0.0.0:0: listen tcp 0.0.0.0:18080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.`
と 拒否されます。

 powershell で
PS C:\Users> netstat -aon | findstr ":18080"　とした結果は
```
  TCP         0.0.0.0:18080          0.0.0.0:0              LISTENING       4
  TCP         [::]:18080             [::]:0                 LISTENING       4
```
これを受けて
``PS C:\Users> Get-Process -Id 4``　とすると
```
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
   8790       0       64       4380                 4   0 System
```

18080ポートにSystemの先約があることが原因ではないでしょうか？

他のポートを開けてもらうか、kabustationからwebsocketサーバーが利用するポートを変更できるようにできないでしょうか？

**Comment by enasu** [comment]
ご回答ありがとうございます。

RESTはうまくいっています。


>>>>>>>>>>>>>>>>>>>>
那須 栄治
>>>>>>>>>>>>>>>>>>>


2024年5月22日(水) 23:14 hori-ryota ***@***.***>:

**Comment by hysdsk** [comment]
@hori-ryota 
> WSL上でのコード実行ではなかったりしますか？

WSLのUbuntu上でcurlを実行して確認したので、そこの疎通は確認できていると思います。
