### ISSUE TITLE
【不具合】kabusapi/sendorder/futureの発注エラーについて

### ISSUE THREAD

**Issue by hmhjapan** [kabucom/kabusapi#713]
■[必須] 不具合事象(概要)
python:
http://localhost:18080/kabusapi/sendorder/future
オーダーを送付して、プログラムはエラーが発生して、異常終了しましたが、
でもkabuステーションで先物オーダーの売買は正常に完了しました。

■[必須] 本来想定されるアクションと事象
下記のように結果とオーダーIDを戻す。
{
  "Result": 0,
  "OrderId": "20200529A01N06848002"
}
まだ、
kabuステーションで先物オーダーの売買は正常に完了します。

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
発生時刻：2023-07-10 16:30:31、常時です。
3ヶ月前に同じソースでもエラーが発生しなかったです。最近常時発生します。

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
　OS：windows 10, excel 2019,サンプル(kabusapi/sample/Python/kabusapi_sendorder_future_new.py)

■[任意] 不備部分のログ
呼び出すパラメータ：
Params.token:4bd5c3161bb24c6787f3bba540254db2
Params.Password:password 
Params.Symbol:168090019
Params.Exchange:24
Params.TradeType:1
Params.TimeInForce:2
Params.Side:1 
Params.Qty:1 
Params.FrontOrderType:120
Params.Price:0
Params.ExpireDay:0
エラーログ：
2023-07-10 16:30:31,006  ,######################################################## 
2023-07-10 16:30:31,006  ,error method:FDecisionMakingPoint.CaculWarnFlag。计算警戒价格！ 
2023-07-10 16:30:31,006  ,关键价格主处理失败: ,AttributeError("'NoneType' object has no attribute 'write'") 
2023-07-10 16:30:31,006  ,错误文件: ,C:\Users\zaoba\AppData\Local\Temp\_MEI23922\PGM\FLayer\QuantitativeTrading\FDecisionMakingPoint.pyc 
2023-07-10 16:30:31,007  ,错误行数: ,8397 
2023-07-10 16:30:31,007  ,调试信息： 
Traceback (most recent call last):
  File "PGM\FLayer\Kabu\FKabusapi.py", line 58, in SendOrderFuture
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PGM\FLayer\QuantitativeTrading\FDecisionMakingPoint.py", line 8397, in CaculWarnFlag
  File "PGM\FLayer\QuantitativeTrading\FDecisionMakingPoint.py", line 12327, in CreateOrderKabus
  File "PGM\FLayer\Kabu\FKabusapi.py", line 70, in SendOrderFuture
  File "pprint.py", line 53, in pprint
  File "pprint.py", line 148, in pprint
  File "pprint.py", line 185, in _format
AttributeError: 'NoneType' object has no attribute 'write'
2023-07-10 16:30:31,008  ,######################################################## 

エラー原因の解析をよろしくお願いいたします。

**Comment by hmhjapan** [comment]
# 下記の成行オーダーのパラメーター設定をご参考ください。
    Params.token='Token'
    Params.Password = 'password'
    Params.Symbol ='168090019'   # '167060019'  
    Params.Exchange = '24'       　　#24 #24 夜間;　23	日中;2日通し
    Params.TradeType = 1      　　  # 1:新規 2:返済
    Params.TimeInForce = 2      　  # 1:FAS 2:FAK 3:FOK
    Params.FrontOrderType = 120 # 120
    Params.Price = 0         　　　    # 27200
    Params.Side = 1           　　　   # 1	売; 2	買
    Params.Qty = 1               　　　# 1
    Params.ExpireDay = 0

**Comment by satosato125** [comment]
添付のエラーログですと、APIからどのようなエラーが返却されているのかわかりません。
また、ご使用になっているとおっしゃっているサンプルについてもログに出力されておりません。
申し訳ございませんが、こちらの情報だけではエラーの詳細がわからないため、回答をお出しすることができません。

kabuステーションで売買は正常に完了しているとのことですので、APIは正常終了となっていないか、ご確認をお願いします。
もし、APIが異常終了となっている場合、APIから返却されたエラーコードをご提示ください。

なお、お客さま自身で作成されたプログラムについては、こちらではご質問にお答えできかねますこと、ご容赦ください。

**Comment by hmhjapan** [comment]
ご回答ありがとうございます。
APIから返却されたエラーコードがあるかどうか、再確認します。後に再連絡します。

**Comment by yasuyuki-nakazawa** [comment]
Pythonの”AttributeError("'NoneType' object has no attribute 'write'")とあることから、
APIからの戻り値、もしくは何らかの処理（プログラムがないので判断できませんが）でNoneだった場合の考慮が不足していたために発生している要にも見えますが、この観点でプログラムをご確認されてみてはいかがでしょうか

**Comment by cooperallwin** [comment]
返事がおそくてすみません。
結論として、自分ソースに問題がりますが、サンプルソースの一部分を入れ替えました。
原因がまだわからないですが、解決方法を見つけました。
(https://github.com/kabucom/kabusapi/blob/master/sample/Python/kabusapi_sendorder_future_new.py)について、下記のように書いてあります。
try:
    with urllib.request.urlopen(req) as res:
        print(res.status, res.reason)
        for header in res.getheaders():
            print(header)
        print()
        content = json.loads(res.read())
        pprint.pprint(content)
except urllib.error.HTTPError as e:
    print(e)
    content = json.loads(e.read())
    pprint.pprint(content)
except Exception as e:
    print(e)

解決方法は：サンプルソースのprint()関数を使わないで、ログの出力は自分で作った関数を使うことです。
　例：self.LogR.WriteLogInfo('SendOrderFuture处理失败:',repr(e))
そうしますと、エラーはなくなりました。
ありがとうございます。本件についてクローズしてもいいです。もしエラーが再発生すれば、まだ連絡します。

**Comment by satosato125** [comment]
@cooperallwin 
ご連絡ありがとうございます。
解決済みとのことですので、クローズとさせていただきます。
