### ISSUE TITLE
【質問】 APIの利用制限について

### ISSUE THREAD

**Issue by kura0910** [kabucom/kabusapi#769]
ここ2週間以下のエラーが表示されてAPIを利用した注文ができなくなりました。
APIの利用が制限されているのでしょうか。
もし、APIの利用が制限されているのであれば、解除いただくことは可能でしょうか。
また、制限された理由も教えていただけると幸いです。
お忙しいところ恐縮ですが、どうぞよろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
APIで発生しているエラーメッセージを連携頂けますでしょうか

**Comment by kura0910** [comment]
以下にエラーメッセージを添付します。

HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "FuncForKabuExe.py", line 11, in <module>
    cash = get_cashbalance(token,symbol=None)
  File "..\tradeSystem\FuncForKabu.py", line 36, in get_cashbalance
    response = requests.get(url, headers={'X-API-KEY': token,})
  File "C:\Users\Kura\Anaconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Kura\Anaconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Kura\Anaconda3\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "C:\Users\Kura\Anaconda3\lib\site-packages\requests\sessions.py", line 498, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Kura\Anaconda3\lib\site-packages\requests\models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "C:\Users\Kura\Anaconda3\lib\site-packages\requests\models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "C:\Users\Kura\Anaconda3\lib\site-packages\requests\utils.py", line 1040, in check_header_validity
    _validate_header_part(header, value, 1)
  File "C:\Users\Kura\Anaconda3\lib\site-packages\requests\utils.py", line 1050, in _validate_header_part
    f"Header part ({header_part!r}) from {header} "
requests.exceptions.InvalidHeader: Header part (<HTTPError 401: 'Unauthorized'>) from ('X-API-KEY', <HTTPError 401: 'Unauthorized'>) must be of type str or bytes, not <class 'urllib.error.HTTPError'>

**Comment by yasuyuki-nakazawa** [comment]
過去に当該エラーが発生するケースを確認しました。
カブステｰション側がログアウトされているということはないかご確認頂けますでしょうか。
