### ISSUE TITLE
【要望】WebSocket のping/pong対応

### ISSUE THREAD

**Issue by Ros522** [kabucom/kabusapi#8]
WebSocketプロトコルの標準に沿ったping/pongへの対応を要望いたします
https://tools.ietf.org/html/rfc6455#section-5.5.2

現状、Pythonのwebsocketsライブラリを始めとした、標準でpingによるハートビートが有効になっているライブラリを用いて接続した場合に、一定時間後にコネクションクローズとなってしまいます。
ライブラリ側でping機能を無効にすることで回避できますが、何らかの形でハートビートを行えるような機能追加を要望いたします。

                async with websockets.connect("ws://localhost:18080/kabusapi/websocket",ping_interval=1) as ws:
                    while not ws.closed:
                        data = await ws.recv()
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\aiokabucom.py", line 143, in run
    data = await ws.recv()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websockets\protocol.py", line 509, in recv
    await self.ensure_open()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websockets\protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by yasuyuki-nakazawa** [comment]
要望として承りました。検討させていただきます。
